### ISSUE TITLE
x64 dump of x86 process fail to emulate

### ISSUE THREAD

**Issue by thewhitegoatcb** [mrexodia/dumpulator#10]
I have noticed if you do a dump on x64 OS of a x86 process (from task manager or procdump64 for example) dumpulator would try to emulate everything in x64 even though most of the dump is actually x86 causing some unexpected behavior, it doesn't happen if you do a x86 dump from x32dbg or from procdump(32).

**Comment by thewhitegoatcb** [comment]
I have compiled the StringEncryptionFun in x86-Release to test this, the crash is pretty simple in this one because it tries to run in x64 and so doesn't setup the stack for x86 calling convention (passes arguments via registers rather than the stack).

![image](https://user-images.githubusercontent.com/69012729/152647381-23f02064-3cea-4e35-af68-5a1aa08d9350.png)
Im not sure where IDA is reading "Segment bitness" from as I couldn't really find much in the dmp.

[StringEncryptionFun32_wow64.zip](https://github.com/mrexodia/dumpulator/files/8008245/StringEncryptionFun32_wow64.zip)

It's not a pressing issue since you can still do x86 dump on any system it's just unexpected.

**Comment by mrexodia** [comment]
This would need additional work in the form of proper WOW64 support. It requires setting up the GDT properly and additional infrastructure to handle the WOW64 syscalls (currently it's super hacked by just hooking the WOW64 transition pointer).

**Comment by mrexodia** [comment]
This should be implemented with the new exception support.
