### ISSUE TITLE
Dumpulator takes a long time to load when handling large dumps

### ISSUE THREAD

**Issue by gakar06** [mrexodia/dumpulator#35]
Feature Request: Please look into addressing the issue where large dump files aren't easily processed by dumpulator.

Description: Dumpulator is taking an excessively long time to load a dump file of 40MB. I was testing the decryption of an RC4 encrypted configuration block from gh0stRAT. I dumped out the process and it was 40MB. I fed this dump into dumpulator and it was still trying to load after 20 minutes.

Sample: https://www.virustotal.com/gui/file/0a9c881b857d4044cb6dfeba682190d7d9dc6ef94bc149cac77f3e0f65e9c69a

**Comment by mrexodia** [comment]
Yeah, this is something I've been looking into. Locally I have some changes related to it, but it requires a bit of a rewrite. The main issue (which is becoming a bit of a recurring theme) is that unicorn has a memory allocation strategy that's O(n). This means that you get effectively O(n^2) when allocating all the ranges. I did a test and allocating a 1000 ranges takes 600 seconds or something ridiculous like that.

The solution is to keep our own memory map (which is already done to a great extent) and lazily map the pages into unicorn when we get a fetch exception. This can definitely be done, but it requires some work to do cleanly and some heuristics to not tank performance completely (you want to map whole regions for example, not single pages).

**Comment by c4sku7** [comment]
May I ask when will this problem be solved? I loaded a 80MB file, and it took nearly an hour to finish, so I had to give up.

**Comment by mrexodia** [comment]
Whenever I have time. Currently I’m on vacation.

**Comment by mrexodia** [comment]
@c4sku7 @gakar06 could you try again with https://github.com/mrexodia/dumpulator/pull/36 this issue should be largely mitigated. I tested on a 4GB dump and it takes around 25 seconds to load. Not perfect, but previously it took something like 45 minutes...
